name: pulsehub
description: "A new Flutter project."
publish_to: "none"
version: 0.0.7+8

environment:
  sdk: ^3.6.1

dependencies:
  board_datetime_picker: ^2.3.0
  cached_network_image: ^3.4.1
  cookie_jar: ^4.0.8
  csv: ^6.0.0
  curved_labeled_navigation_bar: ^2.0.5
  dio: ^5.7.0
  dio_cookie_manager: ^3.1.1
  envied: ^1.0.1
  equatable: ^2.0.7
  file_picker: ^8.1.7
  fl_chart: ^0.70.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_exit_app: ^1.1.4
  flutter_markdown: ^0.7.4+3
  flutter_material_design_icons: ^1.1.7447
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.2
  flutter_speed_dial: ^7.0.0
  flutter_svg: ^2.0.16
  fluttertoast: ^8.2.8
  fpdart: ^1.1.1
  get_it: ^8.0.2
  go_router: ^14.6.2
  image: ^4.1.7
  image_picker: ^1.0.7
  injectable: ^2.5.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  local_auth: ^2.3.0
  lucide_icons: ^0.257.0
  matrix_gesture_detector: ^0.2.0-nullsafety.1
  path: ^1.9.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  pinput: ^5.0.0
  qr_flutter: ^4.1.0
  screwdriver: ^5.9.0
  share_plus: ^10.1.3
  shared_preferences: ^2.3.5
  skeletonizer: ^1.4.2
  touchable: ^1.0.2
  url_launcher: ^6.3.1
  wolt_modal_sheet: ^0.10.0

dev_dependencies:
  build_runner: ^2.4.13
  change_app_package_name: ^1.4.0
  envied_generator: ^1.0.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
